version: 1

formatters:
  standard:
    format: '[%(asctime)s] [%(levelname)s] %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  errorFile:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  infoLogger:
    level: INFO
    handlers: [console]
    propagate: no

  errorLogger:
    level: ERROR
    handlers: [console, errorFile]
    propagate: no
  